services:
  app:
    build: 
      context: .
      dockerfile: ./container/app/Dockerfile
    ports:
      - 3000:3000
      - 6006:6006
    tty: true
    stdin_open: true
    volumes:
      - ./src:/home/node/app
